#!/usr/bin/env python3
"""Build-time: pack robot_cfg/<name>/<name>.cfg into a C++ translation unit."""
from __future__ import annotations

import pathlib
import sys


def pick_delimiter(text: str) -> str:
    base = "ROBOT_CFG_JSON"
    for i in range(0, 100):
        delim = base if i == 0 else f"{base}_{i}"
        token = f"){delim}("
        if token not in text:
            return delim
    raise RuntimeError("Could not find safe raw-string delimiter for embedded cfg")


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_robot_cfgs.py <robot_cfg_dir> <output.cpp>", file=sys.stderr)
        return 2
    root = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[2])
    entries: list[tuple[str, str, str]] = []
    if not root.is_dir():
        print(f"robot_cfg dir missing: {root}", file=sys.stderr)
        return 1
    for d in sorted(root.iterdir()):
        if not d.is_dir():
            continue
        name = d.name
        cfg = d / f"{name}.cfg"
        if not cfg.is_file():
            continue
        text = cfg.read_text(encoding="utf-8")
        delim = pick_delimiter(text)
        entries.append((name, text, delim))
    if not entries:
        print(f"no */*.cfg found under {root}", file=sys.stderr)
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "// AUTO-GENERATED by scripts/cmake/embed_robot_cfgs.py — do not edit.",
        '#include "rokae_header/robot_cfg_embedded.hpp"',
        "#include <string_view>",
        "",
        "namespace RokaeApi {",
        "namespace RobotCfgEmbedded {",
        "",
    ]
    for name, text, delim in entries:
        sym = "".join(ch if ch.isalnum() else "_" for ch in name)
        lines.append("static constexpr char k_cfg_" + sym + '[] = R"' + delim + "(")
        lines.append(text)
        if not text.endswith("\n"):
            lines.append("\n")
        lines.append(")" + delim + "\";")
        lines.append("")
    lines.append("struct Entry {")
    lines.append("  std::string_view name;")
    lines.append("  std::string_view json;")
    lines.append("};")
    lines.append("")
    lines.append("static constexpr Entry kEntries[] = {")
    for name, _text, _delim in entries:
        sym = "".join(ch if ch.isalnum() else "_" for ch in name)
        lines.append(
            "  {std::string_view{\"" + name + "\"}, "
            "std::string_view{k_cfg_" + sym + ", sizeof(k_cfg_" + sym + ") - 1}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("std::string_view GetEmbeddedRobotCfgJson(std::string_view model_name) {")
    lines.append("  size_t lo = 0, hi = sizeof(kEntries) / sizeof(kEntries[0]);")
    lines.append("  while (lo < hi) {")
    lines.append("    size_t mid = (lo + hi) / 2;")
    lines.append("    int cmp = model_name.compare(kEntries[mid].name);")
    lines.append("    if (cmp == 0) return kEntries[mid].json;")
    lines.append("    if (cmp < 0) hi = mid;")
    lines.append("    else lo = mid + 1;")
    lines.append("  }")
    lines.append("  return std::string_view{};")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace RobotCfgEmbedded")
    lines.append("}  // namespace RokaeApi")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
